import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

import "@fortawesome/fontawesome-svg-core/styles.css";

import { config } from "@fortawesome/fontawesome-svg-core";
import Footer from "@/components/Footer/Footer";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
import { allProvider } from "@/context/allContext";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <allProvider>
          <AuthProvider>
            <div className=" ">
              <header>
                <Navbar />
              </header>

              <main>{children}</main>

              <footer>
                <Footer />
              </footer>
            </div>
          </AuthProvider>
        </allProvider>
      </body>
    </html>
  );
}
